import argparse
import json
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_MODEL = REPO_ROOT / "eog_1dcnn_int8.tflite"
DEFAULT_OUTPUT_CPP = REPO_ROOT / "m55m1_deploy" / "Model" / "NN_Model_INT8.tflite.cpp"
DEFAULT_SUMMARY = REPO_ROOT / "m55m1_deploy" / "eog_model_summary.json"
TFLM_ROOT = Path(
    r"C:\Users\User\Desktop\ML_M55M1_SampleCode\M55M1BSP-3.01.003\ThirdParty\tflite_micro"
)


def add_tflite_schema_paths() -> None:
    flatbuffers_py = TFLM_ROOT / "_deps" / "tensorflow-flatbuffers-src" / "python"
    schema_py = TFLM_ROOT / "tensorflow" / "lite" / "python"

    if not flatbuffers_py.exists() or not schema_py.exists():
        raise FileNotFoundError(
            "Cannot find the local TFLite schema helper files under "
            f"{TFLM_ROOT}. Check your ML_M55M1_SampleCode path."
        )

    sys.path.insert(0, str(flatbuffers_py))
    sys.path.insert(0, str(schema_py))


def bytes_to_cpp_array(buf: bytes) -> str:
    lines = []
    for i in range(0, len(buf), 16):
        chunk = buf[i : i + 16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(lines)


def inspect_model(model_path: Path) -> dict:
    add_tflite_schema_paths()
    import schema_py_generated as schema

    buf = model_path.read_bytes()
    model = schema.Model.GetRootAsModel(buf, 0)
    subgraph = model.Subgraphs(0)

    builtin_names = {
        value: name
        for name, value in schema.BuiltinOperator.__dict__.items()
        if not name.startswith("_") and isinstance(value, int)
    }

    def tensor_summary(tensor_index: int) -> dict:
        tensor = subgraph.Tensors(tensor_index)
        quant = tensor.Quantization()
        return {
            "tensor_index": tensor_index,
            "name": tensor.Name().decode("utf-8"),
            "shape": [tensor.Shape(i) for i in range(tensor.ShapeLength())],
            "type": tensor.Type(),
            "quantization": {
                "scale": [quant.Scale(i) for i in range(quant.ScaleLength())]
                if quant
                else [],
                "zero_point": [quant.ZeroPoint(i) for i in range(quant.ZeroPointLength())]
                if quant
                else [],
            },
        }

    operators = []
    for i in range(subgraph.OperatorsLength()):
        op = subgraph.Operators(i)
        opcode = model.OperatorCodes(op.OpcodeIndex())
        builtin_code = opcode.BuiltinCode()
        operators.append(
            {
                "index": i,
                "builtin_code": builtin_code,
                "builtin_name": builtin_names.get(builtin_code, "UNKNOWN"),
                "version": opcode.Version(),
            }
        )

    return {
        "model_path": str(model_path),
        "model_size_bytes": len(buf),
        "inputs": [tensor_summary(subgraph.Inputs(i)) for i in range(subgraph.InputsLength())],
        "outputs": [tensor_summary(subgraph.Outputs(i)) for i in range(subgraph.OutputsLength())],
        "operators": operators,
    }


def write_cpp_source(model_path: Path, output_cpp: Path) -> None:
    model_bytes = model_path.read_bytes()
    cpp_text = f"""/*
 * Autogenerated from {model_path.name}. Do not edit by hand.
 */

#include "Model.hpp"
#include "BufAttributes.hpp"

namespace arm {{
namespace app {{
namespace nn {{

static const uint8_t nn_model[] MODEL_TFLITE_ATTRIBUTE =
{{
{bytes_to_cpp_array(model_bytes)}
}};

const uint8_t* GetModelPointer()
{{
    return nn_model;
}}

size_t GetModelLen()
{{
    return sizeof(nn_model);
}}

}} /* namespace nn */
}} /* namespace app */
}} /* namespace arm */
"""

    output_cpp.parent.mkdir(parents=True, exist_ok=True)
    output_cpp.write_text(cpp_text, encoding="utf-8", newline="\n")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate M55M1 deployment artifacts for the EOG int8 TFLite model."
    )
    parser.add_argument("--model", type=Path, default=DEFAULT_MODEL)
    parser.add_argument("--output-cpp", type=Path, default=DEFAULT_OUTPUT_CPP)
    parser.add_argument("--summary", type=Path, default=DEFAULT_SUMMARY)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not args.model.is_file():
        raise FileNotFoundError(f"Model not found: {args.model}")

    summary = inspect_model(args.model)
    args.summary.parent.mkdir(parents=True, exist_ok=True)
    args.summary.write_text(json.dumps(summary, indent=2), encoding="utf-8", newline="\n")
    write_cpp_source(args.model, args.output_cpp)

    print(f"Wrote summary: {args.summary}")
    print(f"Wrote model source: {args.output_cpp}")


if __name__ == "__main__":
    main()
